version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
      - nginx_volume:/app/website/nginx
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
      - nginx_volume:/app/website/nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  nginx_volume: