version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
    ports:
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: