# Generated by Django 3.2.9 on 2021-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='parser',
            name='patterns',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='parser',
            name='site',
            field=models.CharField(default='', max_length=256),
        ),
    ]
