# Generated by Django 3.2.9 on 2022-01-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='itemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_heading_items', models.CharField(max_length=80)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.category')),
            ],
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_link', models.CharField(max_length=80)),
                ('link_page', models.CharField(default='', max_length=80)),
                ('importance', models.CharField(max_length=16)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.itemname')),
            ],
        ),
    ]
