# Generated by Django 3.2.9 on 2022-02-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20220211_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(max_length=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='pages',
            name='importance',
        ),
        migrations.AddField(
            model_name='blocks',
            name='id_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.categorys'),
        ),
        migrations.AddField(
            model_name='pages',
            name='id_params',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.params'),
        ),
    ]
