# Generated by Django 3.2.9 on 2022-02-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20220211_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='params',
            new_name='importance',
        ),
    ]
