# Generated by Django 3.2.9 on 2022-02-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_rename_params_importance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='importance',
            new_name='params',
        ),
    ]
