# Generated by Django 3.2.9 on 2022-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_rename_importance_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
