# Generated by Django 3.2.9 on 2022-02-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_auto_20220211_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='id_params',
        ),
        migrations.AddField(
            model_name='itemname',
            name='id_params',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.params'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
