# Generated by Django 3.2.9 on 2022-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_auto_20220214_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
